name: dock-app
services:
  backend:
    build: ./backend
    networks:
      - mern_network
    restart: unless-stopped
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules 
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - mern_network
    restart: unless-stopped
    depends_on:
      - backend
    

  mongodb:
    image: mongo:latest  
    ports:
      - "27017:27017"  
    networks:
      - mern_network
    volumes:
      - mongo-data:/data/db  
  caddy:
    image: caddy:2-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - mern_network
    depends_on:
      - frontend
      - backend

networks:
  mern_network:
    driver: bridge 

volumes:
  mongo-data:
    driver: local 
  caddy_data:
  caddy_config: